# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181003_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('used', models.BooleanField()),
            ],
            options={
                'db_table': 'coupon',
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employeetype',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='EmployeeType',
        ),
    ]
