# Generated by Django 2.1.2 on 2018-11-28 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181128_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='number',
        ),
    ]
